main/config: require '.' at the end of the virtPrefix
This avoids a very goofy bug where it appears that all queries return the
error: '"" is not a valid tag'.